<a href="https://colab.research.google.com/github/aadhamashraf/CareerMatch-AI/blob/main/ai-features%20/1.%20CV%20Parsing%20%26%20Section%20Detection/cv_parsing_section_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()


In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

aadhamashraf_technical_cv_augmented_ollama_csv_path = kagglehub.dataset_download('aadhamashraf/technical-cv-augmented-ollama-csv')
aadhamashraf_adham_ashraf_eltholth_pdf_path = kagglehub.dataset_download('aadhamashraf/adham-ashraf-eltholth-pdf')

print('Data source import complete.')


In [ ]:
!pip install pdfplumber docx2txt transformers torch scikit-learn


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 73.9 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 77.5 MB/s eta 0:00:00:00:01


In [ ]:
import pdfplumber
import docx2txt

def extract_text_from_file(file_path):
    if file_path.endswith(".pdf"):
        text = ""
        with pdfplumber.open(file_path) as pdf:
            for page in pdf.pages:
                text += page.extract_text() + "\n"
    elif file_path.endswith(".docx"):
        text = docx2txt.process(file_path)
    else:
        raise ValueError("Unsupported file format. Please upload PDF or DOCX.")
    return text

In [ ]:
import re

def split_text_into_sentences(text):
    sentences = re.split(r'\n+|(?<=[.!?])\s+', text.strip())
    return [s.strip() for s in sentences if len(s.strip()) > 10]

In [ ]:
!pip install spacy regex
!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 2.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of mkl-fft to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mkl-random to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of mkl-umath to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 84.9 MB/s eta 0:00:00:00:0100:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.12.0 requires google-cloud-bigquery-storage<3.0.0,>=2.3

In [ ]:
import spacy
import re
import pandas as pd

nlp = spacy.load("en_core_web_sm")

# Regex patterns
EMAIL_PATTERN = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
PHONE_PATTERN = re.compile(r"(\+?\d[\d\-\s]{8,}\d)")
LINK_PATTERN = re.compile(r"(https?://[^\s]+|www\.[^\s]+|linkedin\.com/[^\s]+|github\.com/[^\s]+)")
LOCATION_PATTERN = re.compile(r"\b(giza|cairo|egypt|october|road|street|gardens|city)\b", re.IGNORECASE)

ABOUT_KEYWORDS = [
    "passionate", "motivated", "enthusiastic", "aim", "interested",
    "seeking", "driven", "goal", "focused", "dedicated", "looking for",
    "about me", "profile", "summary", "objective", "career", "mission",
    "curious", "exploring", "strive", "learn", "innovation", "impactful"
]

def is_personal_info(text):
    text_lower = text.lower()
    if EMAIL_PATTERN.search(text) or PHONE_PATTERN.search(text) or LINK_PATTERN.search(text):
        return True
    if LOCATION_PATTERN.search(text_lower):
        return True
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            return True
        if ent.label_ in ["GPE", "LOC"] and len(text.split()) <= 10:
            return True
    # Avoid marking education lines (degree, university)
    if any(word in text_lower for word in ["bachelor", "university", "science", "degree", "school"]):
        return False
    return False


def is_about_section(text):
    text_lower = text.lower().strip()
    if any(kw in text_lower for kw in ABOUT_KEYWORDS):
        return True
    if len(text.split()) > 6 and any(p in text_lower for p in ["i ", "my ", "me "]):
        return True
    if text_lower.startswith("a ") and any(k in text_lower for k in ["developer", "engineer", "student", "researcher"]):
        return True
    return False


def enhance_labels(df):
    final_labels = []
    last_about = -5  # to track section continuity

    for idx, row in df.iterrows():
        text = str(row["text"]).strip()
        ml_label = row["predicted_label"]

        if is_personal_info(text):
            label = "Personal_Info"
        elif is_about_section(text):
            label = "About"
            last_about = idx
        elif idx - last_about <= 2 and len(text.split()) < 15:
            # continue About section for next 1–2 short lines
            label = "About"
        else:
            label = ml_label

        final_labels.append(label)

    df["final_label"] = final_labels
    return df

In [ ]:
# from transformers import pipeline

# classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# labels = ["Education", "Experience", "Projects", "Skills", "Certifications"]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu


In [ ]:
# def classify_cv_text(sentences):
#     results = []
#     for sentence in sentences:
#         pred = classifier(sentence, labels)
#         label = pred["labels"][0]
#         score = pred["scores"][0]
#         results.append({"text": sentence, "category": label, "confidence": round(score, 3)})
#     return results

In [ ]:
file_path = "/kaggle/input/adham-ashraf-eltholth-pdf/Adham_Ashraf_Eltholth.pdf"
text = extract_text_from_file(file_path)
sentences = split_text_into_sentences(text)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

df = pd.read_csv("/kaggle/input/technical-cv-augmented-ollama-csv/technical_cv_augmented_ollama.csv")
assert 'text' in df.columns and 'label' in df.columns, "Dataset must contain 'text' and 'label' columns."
df['label'] = df['label'].astype(str)

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state=42, stratify=df['label'])

vectorizer = TfidfVectorizer(stop_words='english', max_features=5000, ngram_range=(1, 2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

models = {
    "Decision Tree": DecisionTreeClassifier(max_depth=50, random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=200, random_state=42)
}

for name, model in models.items():
    print(f"\nTraining {name}...")
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)
    print(f"\n{name} Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Training Decision Tree...

Decision Tree Accuracy: 0.9667
                precision    recall  f1-score   support

Certifications       0.98      0.99      0.98       154
     Education       1.00      0.99      1.00       158
    Experience       1.00      0.92      0.96       156
      Projects       0.88      0.99      0.93       153
        Skills       0.98      0.95      0.96       159

      accuracy                           0.97       780
     macro avg       0.97      0.97      0.97       780
  weighted avg       0.97      0.97      0.97       780

Confusion Matrix:
 [[152   0   0   2   0]
 [  0 157   0   0   1]
 [  0   0 143  13   0]
 [  0   0   0 151   2]
 [  3   0   0   5 151]]

Training Random Forest...

Random Forest Accuracy: 0.9500
                precision    recall  f1-score   support

Certifications       1.00      1.00      1.00       154
     Education       1.00      0.99      1.00       158
    Experience       1.00      0.89      0.94       156
      Projects 

In [ ]:
sample_text = "Developed a neural network for computer vision tasks"
sample_vector = vectorizer.transform([sample_text])
best_model = models["Gradient Boosting"]
print("\nPredicted label:", best_model.predict(sample_vector)[0])

hard_samples = [
    ("Developed a neural network for image recognition during my Master’s at MIT.", "Projects"),
    ("Worked as a Data Analyst intern while completing my bachelor’s in Computer Science.", "Experience"),
    ("Implemented a web app to visualize stock data using React and Python.", "Projects"),
    ("Earned AWS Certified Solutions Architect after developing multiple cloud-based apps.", "Certifications"),
    ("Trained in machine learning through Coursera and applied concepts in a deep learning project.", "Education"),
    ("Led a team of 4 engineers to design a mobile app used by 10K users.", "Experience"),
    ("Built and deployed a recommendation system during an internship at Google.", "Experience"),
    ("Completed a deep learning specialization from Andrew Ng on Coursera.", "Certifications"),
    ("Skilled in Python, TensorFlow, and REST API development.", "Skills"),
    ("Graduated with honors in Electrical Engineering, focusing on control systems.", "Education"),
    ("Designed and implemented a CI/CD pipeline for automated model deployment.", "Projects"),
    ("Volunteered as a robotics instructor, mentoring students in Arduino projects.", "Experience"),
    ("Achieved Microsoft Certified: Azure Fundamentals credential.", "Certifications"),
    ("Developed a mobile fitness tracker app with Flutter and Firebase.", "Projects"),
    ("Mentored junior developers on Python and Git best practices.", "Experience"),
    ("Completed Bachelor’s in Artificial Intelligence with a capstone on NLP models.", "Education"),
    ("Proficient in SQL, Docker, and data visualization tools like Tableau.", "Skills"),
    ("Built an automated resume parser using NLP libraries.", "Projects"),
    ("Obtained TensorFlow Developer Certificate and implemented CNNs.", "Certifications"),
    ("Implemented real-time anomaly detection system for IoT devices during coursework.", "Projects")
]

df_hard = pd.DataFrame(hard_samples, columns=["text", "expected_label"])
X_hard_tfidf = vectorizer.transform(df_hard["text"])
df_hard["predicted_label"] = best_model.predict(X_hard_tfidf)
accuracy = (df_hard["predicted_label"] == df_hard["expected_label"]).mean()
print(f"\nHard Test Accuracy: {accuracy:.2f}")
print(df_hard)
df_hard.to_csv("cv_hard_test_predictions.csv", index=False)
print("Saved hard test results to 'cv_hard_test_predictions.csv'")


Predicted label: Projects

Hard Test Accuracy: 0.50
                                                 text  expected_label  \
0   Developed a neural network for image recogniti...        Projects   
1   Worked as a Data Analyst intern while completi...      Experience   
2   Implemented a web app to visualize stock data ...        Projects   
3   Earned AWS Certified Solutions Architect after...  Certifications   
4   Trained in machine learning through Coursera a...       Education   
5   Led a team of 4 engineers to design a mobile a...      Experience   
6   Built and deployed a recommendation system dur...      Experience   
7   Completed a deep learning specialization from ...  Certifications   
8   Skilled in Python, TensorFlow, and REST API de...          Skills   
9   Graduated with honors in Electrical Engineerin...       Education   
10  Designed and implemented a CI/CD pipeline for ...        Projects   
11  Volunteered as a robotics instructor, mentorin...      Experience  

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

df = pd.read_csv("/kaggle/input/technical-cv-augmented-ollama-csv/technical_cv_augmented_ollama.csv")

assert 'text' in df.columns and 'label' in df.columns, "Dataset must contain 'text' and 'label' columns."

df['label'] = df['label'].astype(str)

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000,
    ngram_range=(1,2)  # Unigrams + bigrams for better feature richness
)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

clf = LogisticRegression(max_iter=200)
clf.fit(X_train_tfidf, y_train)

y_pred = clf.predict(X_test_tfidf)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


sample_text = "Developed a neural network for computer vision tasks"
sample_vector = vectorizer.transform([sample_text])
print("\nPredicted label:", clf.predict(sample_vector)[0])


Accuracy: 1.0

Classification Report:
                 precision    recall  f1-score   support

Certifications       1.00      1.00      1.00       158
     Education       1.00      1.00      1.00       170
    Experience       1.00      1.00      1.00       166
      Projects       1.00      1.00      1.00       127
        Skills       1.00      1.00      1.00       159

      accuracy                           1.00       780
     macro avg       1.00      1.00      1.00       780
  weighted avg       1.00      1.00      1.00       780


Confusion Matrix:
 [[158   0   0   0   0]
 [  0 170   0   0   0]
 [  0   0 166   0   0]
 [  0   0   0 127   0]
 [  0   0   0   0 159]]

Predicted label: Projects


In [ ]:
hard_samples = [
    ("Developed a neural network for image recognition during my Master’s at MIT.", "Projects"),
    ("Worked as a Data Analyst intern while completing my bachelor’s in Computer Science.", "Experience"),
    ("Implemented a web app to visualize stock data using React and Python.", "Projects"),
    ("Earned AWS Certified Solutions Architect after developing multiple cloud-based apps.", "Certifications"),
    ("Trained in machine learning through Coursera and applied concepts in a deep learning project.", "Education"),
    ("Led a team of 4 engineers to design a mobile app used by 10K users.", "Experience"),
    ("Built and deployed a recommendation system during an internship at Google.", "Experience"),
    ("Completed a deep learning specialization from Andrew Ng on Coursera.", "Certifications"),
    ("Skilled in Python, TensorFlow, and REST API development.", "Skills"),
    ("Graduated with honors in Electrical Engineering, focusing on control systems.", "Education"),
    ("Designed and implemented a CI/CD pipeline for automated model deployment.", "Projects"),
    ("Volunteered as a robotics instructor, mentoring students in Arduino projects.", "Experience"),
    ("Achieved Microsoft Certified: Azure Fundamentals credential.", "Certifications"),
    ("Developed a mobile fitness tracker app with Flutter and Firebase.", "Projects"),
    ("Mentored junior developers on Python and Git best practices.", "Experience"),
    ("Completed Bachelor’s in Artificial Intelligence with a capstone on NLP models.", "Education"),
    ("Proficient in SQL, Docker, and data visualization tools like Tableau.", "Skills"),
    ("Built an automated resume parser using NLP libraries.", "Projects"),
    ("Obtained TensorFlow Developer Certificate and implemented CNNs.", "Certifications"),
    ("Implemented real-time anomaly detection system for IoT devices during coursework.", "Projects")
]

df_hard = pd.DataFrame(hard_samples, columns=["text", "expected_label"])
X_hard_tfidf = vectorizer.transform(df_hard["text"])
df_hard["predicted_label"] = clf.predict(X_hard_tfidf)
accuracy = (df_hard["predicted_label"] == df_hard["expected_label"]).mean()
print(f"\nHard Test Accuracy: {accuracy:.2f}")
print(df_hard)
df_hard.to_csv("cv_hard_test_predictions.csv", index=False)
print("Saved hard test results to 'cv_hard_test_predictions.csv'")


Hard Test Accuracy: 0.75
                                                 text  expected_label  \
0   Developed a neural network for image recogniti...        Projects   
1   Worked as a Data Analyst intern while completi...      Experience   
2   Implemented a web app to visualize stock data ...        Projects   
3   Earned AWS Certified Solutions Architect after...  Certifications   
4   Trained in machine learning through Coursera a...       Education   
5   Led a team of 4 engineers to design a mobile a...      Experience   
6   Built and deployed a recommendation system dur...      Experience   
7   Completed a deep learning specialization from ...  Certifications   
8   Skilled in Python, TensorFlow, and REST API de...          Skills   
9   Graduated with honors in Electrical Engineerin...       Education   
10  Designed and implemented a CI/CD pipeline for ...        Projects   
11  Volunteered as a robotics instructor, mentorin...      Experience   
12  Achieved Microsoft Ce

In [ ]:
cv_labels = clf.predict(vectorizer.transform(sentences))

classified_cv = pd.DataFrame({'text': sentences, 'predicted_label': cv_labels})

classified_cv = add_custom_labels(classified_cv)

In [ ]:
for _, row in classified_cv.iterrows():
    print(f"[{row['final_label'].upper()}] {row['text']}")

[PERSONAL_INFO] Adham Ashraf Eltholth
[PERSONAL_INFO] +20 15 50840224 | adham.eltholth@gmail.com | October Gardens, Giza
[PERSONAL_INFO] linkedin.com/in/adham-ashraf | github.com/aadhamashraf
[ABOUT] A multi-passionate computer science and AI undergraduate with a strong foundation in software engineering, machine
[ABOUT] learning, and intelligent systems.
[ABOUT] I aim to bridge the gap between innovation and implementation through meaningful,
[ABOUT] scalable, and impactful tech solutions.
[PERSONAL_INFO] Passionate about AI explainability, full-stack development, and solving real-world
[SKILLS] problems with creative and detail-oriented thinking.
[ABOUT] Actively seeking opportunities to contribute to cutting-edge projects,
[EDUCATION] grow through mentorship, and build futuristic, human-centric technology platforms.
[PERSONAL_INFO] • Zewail City of Science, Technology and Innovation Aug.
[PROJECTS] 2022 – Sept.
[PERSONAL_INFO] Bachelor of Science in Computer Science and Artificial I